name: skynet-typescript-api-stack

displayName: Typescript API Stack

description: A stack de typescript API a capacidade de criação de serviços inteiramente serverless, com lambdas implementadas em Typescript, criação automática de API Gateway, e outros recursos de nuvem.

picture: "stack.png"

category: Backend

compatibility:
  - NodeJS 14.x
  - CDK 1.x 

technologies: ["Typescript", "Lambda", "DynamoDB", "API Gateway"]

about: about.md

useCase: useCase.md