name: crystal-typescript-api-stack

displayName: Typescript API Stack

description: This stack adds a capacity to create entirely serverless services, with lambdas implemented in Typescript, automatic creation of API Gateway, and other cloud features.

picture: "stack.png"

category: Backend

compatibility:
  - NodeJS 14.x
  - CDK 2.x

technologies:
  - Typescript
  - Lambda
  - API Gateway

about: docs/about.md

useCases:
  - title: Basic Template
    content: docs/useCase.md
    stackfile: stackfiles/basic.yaml
  - title: Basic API
    content: docs/useCase.md
    stackfile: stackfiles/basic-openapi.yaml
