name: crystal-typescript-api-stack

displayName: Typescript API Stack

description: A stack de typescript API a capacidade de criação de serviços inteiramente serverless, com lambdas implementadas em Typescript, criação automática de API Gateway, e outros recursos de nuvem.

picture: "stack.png"

category: Backend

compatibility:
  - NodeJS 14.x
  - CDK 2.x

technologies:
  - Typescript
  - Lambda
  - API Gateway

about: docs/about.md

useCase:
  - title: Basic Template
    content: docs/useCase.md
    stackfile: stackfiles/basic.yaml
  - title: Basic API
    content: docs/useCase.md
    stackfile: stackfiles/basic-openapi.yaml
